backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page Content"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
